import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "tax-filing-compliance",
    video_title: "Annual Tax Filing & Compliance Optimization",
    video_description: "Led the complete tax filing strategy for Shree Balaji Enterprises, a manufacturing firm. Re-organized their ledger system, verified historical accounts, and successfully filed annual Income Tax and GST returns. Designed an audit-ready tax preparation pipeline that reduced tax liability by 12% through eligible deductions under Section 80C/80D and local state industrial benefits, while maintaining 100% statutory compliance.",
    tags: ["Taxation", "GST Filing", "Tax Optimization", "Compliance"],
    cover_image: "/project-images/tax_filing.png",
    publish_date: "2026-03-15",
    client_name: "Shree Balaji Enterprises",
    client_image: "/placeholder.svg",
    client_feedback: "Sneha reorganized our tax process completely. Her detail-oriented approach saved us significant tax expenses and gave us peace of mind during compliance audits.",
    video_link: "",
    project_images: ["/project-images/tax_filing.png"],
    category: ["Taxation"],
    duration: "Q1-Q4 FY25",
    software_used: ["Tally Prime", "Excel", "GST Portal", "IT Portal"],
  },
  {
    id: "financial-audit-reconciliation",
    video_title: "Financial Audit & Bank Reconciliation",
    video_description: "Conducted a thorough internal audit and bank ledger reconciliation for Apex Retailers Ltd., a multi-outlet retail business. Reconciled 12 monthly bank accounts containing over 5,000 transactions. Identified and resolved a vendor payment discrepancy of ₹1.5M caused by incorrect manual ledger entries. Established standard operating procedures (SOPs) for daily cash registers and weekly automated reconciliations, significantly reducing monthly closing cycles.",
    tags: ["Auditing", "Reconciliation", "Financial Controls", "Ledger Audit"],
    cover_image: "/project-images/financial_audit.png",
    publish_date: "2026-05-10",
    client_name: "Apex Retailers Ltd.",
    client_image: "/placeholder.svg",
    client_feedback: "Sneha found discrepancies in our vendor ledgers that we had missed for months. She reconciled our bank statements flawlessly and set up checks to prevent future errors.",
    video_link: "",
    project_images: ["/project-images/financial_audit.png"],
    category: ["Auditing"],
    duration: "3 Weeks",
    software_used: ["QuickBooks", "Advanced Excel"],
  },
  {
    id: "payroll-bookkeeping-system",
    video_title: "Automated Bookkeeping & Payroll System Integration",
    video_description: "Implemented a cloud bookkeeping and automated payroll processing system for Zenith Software Solutions, a growing tech startup with 45+ employees. Transitioned the company from manual spreadsheet bookkeeping to Zoho Books. Configured automatic tracking of accounts payable/receivable, automated salary calculations including statutory TDS, PF, and ESIC deductions, and reduced monthly payroll processing time from 5 days to 1 day.",
    tags: ["Bookkeeping", "Payroll Management", "Automation", "Zoho Books"],
    cover_image: "/project-images/payroll_system.png",
    publish_date: "2026-04-01",
    client_name: "Zenith Software Solutions",
    client_image: "/placeholder.svg",
    client_feedback: "Moving our books and payroll to Zoho Books under Sneha's guidance has been a game-changer. Salaries are processed on time, and our financial reporting is now automated.",
    video_link: "",
    project_images: ["/project-images/payroll_system.png"],
    category: ["Bookkeeping"],
    duration: "1 Month",
    software_used: ["Zoho Books", "MS Excel", "Payroll Portal"],
  },
  {
    id: "corporate-financial-statements",
    video_title: "Corporate Financial Statements & MIS Reporting",
    video_description: "Drafted quarterly and annual financial statements—including Balance Sheets, Profit & Loss (P&L) statements, and Cash Flow summaries—for Evolve Innovations. Generated custom MIS reports with visualizations using Excel and Power BI to highlight key performance indicators (KPIs), operational costs, and profit margins. Provided data-backed insights that supported the executive team in securing a series of investor meetings.",
    tags: ["Financial Analysis", "Balance Sheet", "Cash Flow Projections", "P&L Statement"],
    cover_image: "/project-images/financial_statements.png",
    publish_date: "2026-06-20",
    client_name: "Evolve Innovations",
    client_image: "/placeholder.svg",
    client_feedback: "Sneha's reports are exceptionally clear and well-structured. The dashboard she created helped us understand our quarterly expenses and present solid financials to our board.",
    video_link: "",
    project_images: ["/project-images/financial_statements.png"],
    category: ["Financial Analysis"],
    duration: "Continuous",
    software_used: ["Tally Prime", "MS Excel", "Power BI"],
  },
  {
    id: "gst-reconciliation-itc-claim",
    video_title: "GST Reconciliation & Input Tax Credit Recovery",
    video_description: "Conducted a detailed Input Tax Credit (ITC) reconciliation study for Vogue Cart Online, an e-commerce retail supplier. Cross-referenced purchase registers with GSTR-2B and GSTR-3B tax data over 18 months. Identified missing vendor filings and coordinated with suppliers to upload pending invoices, resulting in the successful recovery of ₹800K in previously unclaimed Input Tax Credits.",
    tags: ["Taxation", "GST Portal", "ITC Claim", "Reconciliation"],
    cover_image: "/project-images/gst_reconciliation.png",
    publish_date: "2026-02-28",
    client_name: "Vogue Cart Online",
    client_image: "/placeholder.svg",
    client_feedback: "Her thoroughness saved us ₹800,000. She followed up with vendors directly and handled the ITC recovery process with absolute expertise.",
    video_link: "",
    project_images: ["/project-images/gst_reconciliation.png"],
    category: ["Taxation", "Bookkeeping"],
    duration: "2 Weeks",
    software_used: ["MS Excel", "Tally Prime", "GST Portal"],
  },
];
